// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhwmgjyrshdvlngaxgfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRod21nanlyc2hkdmxuZ2F4Z2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzAyMDMsImV4cCI6MjA1ODUwNjIwM30.mggw5CtBxPW_M5uwcx3o2eS5z4Tb6GXOvHOcyxeRTfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);